import NavMenuWrapper from "@/components/NavMenuWrapper";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <NavMenuWrapper>
          <Navbar />
          <div> {children}</div>
        </NavMenuWrapper>
      </body>
    </html>
  );
}
