import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import useAuthState from "@/lib/hooks/useAuthState";
import { auth } from "./firebase";
import Providers from "../lib/provider";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";

const mont = Nunito({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "tripConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <Providers>
          <Suspense fallback={null}>
            <div>
              {children}
              <Toaster />
            </div>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
